default_install_hook_types: [pre-commit, commit-msg]  # pre-push
default_language_version:
    python: python3.9

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev:  v3.15.2
    hooks:
    -   id: pyupgrade
        args: ["--py39-plus", "--keep-runtime-typing"]
        stages: [commit]

-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        stages: [commit]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev:  v0.3.4
    hooks:
    -   id: ruff
        args:
        - --fix
        stages: [commit]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v4.5.0
    hooks:
    -   id: fix-byte-order-marker
        stages: [commit]
    -   id: trailing-whitespace
        stages: [commit]
        exclude: ".bumpversion.cfg"
    -   id: end-of-file-fixer
        stages: [commit]
    -   id: check-yaml
        stages: [commit]
        args: ["--unsafe"]
    -   id: check-toml
        stages: [commit]
