name: publish

on:
  push:
    branches: [main]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the dfa-fastapi Docker image
        run: |
          docker build . --tag ghcr.io/korawica/dfa-fastapi:latest
          docker push ghcr.io/korawica/dfa-fastapi:latest

      - name: Test
        run: |
          docker pull ghcr.io/korawica/dfa-fastapi:latest
          docker run ghcr.io/korawica/dfa-fastapi:latest
