name: publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the dfa-fastapi Docker image
        run: |
          docker build . --tag ghcr.io/ddeutils/dfa-fastapi:latest
          docker push ghcr.io/ddeutils/dfa-fastapi:latest

      - name: Test Running the dfa-fastapi Docker image
        run: |
          docker pull ghcr.io/ddeutils/dfa-fastapi:latest
          docker run -d \
            --name dfa-fastapi-local \
            -p 8000:8000 \
            ghcr.io/ddeutils/dfa-fastapi:latest
          docker ps -a

  test-image:
    needs: [publish]
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      dfa-fastapi:
        image: ghcr.io/ddeutils/dfa-fastapi:latest
        ports:
          - 8000:8000
    steps:
      - name: Install Curl for Request Application
        run: |
          apt-get update
          apt-get install curl -y

      - name: Test Request to Application
        run: |
          curl dfa-fastapi:8000/health/ > curl_result
          cat curl_result
